src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     *
     * @Vich\UploadableField(mapping="article_image", fileNameProperty="imageName")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="Article")
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category;
    }

    public function setCategoryId(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }
        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

templates/Front/article.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="card mt-4">
            <h1 class="card-header bg-redchiefs text-light">     {{ article.title }}</h1>

            <div class="card-body">
                <p class="category btn btn-danger">{{ article.categoryId.name }}</p>
                <p class="font-italic"> Par <span
                            class="text-redchiefs font-weight-bold">{{ article.userId.username }}</span>
                    le {{ article.createdat|localizeddate('none', 'none', null, timezone, 'eeee d MMMM Y à HH:mm') }}
                </p>
                {% if article.imagename %}
                    <img class="float-md-right ml-4 mb-4"
                         src="{{ vich_uploader_asset(article,'imageFile')|imagine_filter('article') }}" alt="{{ article.title}} illustration ">
                {% else %}
                    <img class="float-md-right ml-4 mb-4" src="{{ asset('img/jagschiefs.jpg') }}">
                {% endif %}
                <p> {{ article.content|html }}</p>
            </div>
        </div>

        <div class="card mt-4 mb-4">
            <h2 class="card-header bg-yellowchiefs"> Commentaires</h2>
            <div class="card-body">
                {% if is_granted("ROLE_USER") %}
                    <h3>Ajouter un commentaire</h3>
                    <p>{{ form_start(formComment) }}
                        {{ form_errors(formComment.content) }}
                        {{ form_widget(formComment.content,{'attr': {'placeholder': 'Votre Commentaire'}}) }}
                        {{ form_help(formComment.content) }}</p>
                    <button type="submit" class="btn bg-yellowchiefs">Ajouter un commentaire</button>
                    {{ form_end(formComment) }}
                {% endif %}

                {% block comments %}

                    <div id="ajax-results">Pas de Commentaires</div>
                    <div class="navigation_comments">
                        <ul class="pagination pagination_comments">
                            <li class="page-item previous_comments_item">
                                <button class="page-link previous_comments">Précédent</button>
                            </li>
                            <li><span id="pagenum">Numero De page</span></li>
                            <li class="page-item next_comments_item">
                                <button
                                        class="page-link next_comments"> Suivant
                                </button>
                            </li>
                        </ul>
                    </div>
                {% endblock %}
            </div>
        </div>

    </div>
{% endblock %}

{% block javascripts %}
    <script>
        let page = 0;
        getComments(page);
        $('.next_comments').on('click', () => {
            page = page + 1;
            getComments(page);
        });

        $('.previous_comments').on('click', () => {
            page = page - 1;
            getComments(page);
        });

        function getComments(page) {
            let urlTarget = '{{ (path('article_comments',{id: article.id,page: 12354})) }}';
            urlTarget = urlTarget.replace("12354", page);
            $.ajax({
                url: urlTarget,
                type: "POST",
                dataType: "json",
                success: function (data) {
                    $('#ajax-results').html(data[0]);
                    $('#pagenum').html(page + 1);
                    if (data[1] === true) {
                        $('.navigation_comments').show();
                    } else {
                        $('.navigation_comments').hide();
                    }

                    if (data[2] === true) {
                        $('.previous_comments').prop("disabled", false);
                        $('.previous_comments_item').removeClass("disabled");
                    } else {
                        $('.previous_comments').prop("disabled", true);
                        $('.previous_comments_item').addClass("disabled");
                    }

                    if (data[3] === true) {
                        $('.next_comments').prop("disabled", false);
                        $('.next_comments_item').removeClass("disabled");
                    } else {
                        $('.next_comments').prop("disabled", true);
                        $('.next_comments_item').addClass("disabled");
                    }
                },
                error: function () {
                    $('#ajax-results').html("Erreur d'affichage des commentaires");
                }
            });
        }
    </script>
{% endblock %}

templates/Front/articles.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1> Actualités</h1>
        {% for article in articles %}
            <div class="card mt-4">
                <h2 class="card-header bg-redchiefs text-light">
                    <a class="text-light" href="{{ path('article', {id: article.id}) }}"> {{ article.title }} </a>
                </h2>
                <div class="card-body">
                    <p class="category btn btn-danger">{{ article.categoryId.name }}</p>
                    <div class="row no-gutters">
                        {%  if article.imagename %}
                        <div class="col-md-4">

                            <img src="{{ vich_uploader_asset(article,'imageFile')|imagine_filter('article_thumb') }}" height="170" width="250" alt="{{ article.title }} thumbnail"/>
                        </div>
                        {%  endif %}
                        <div class="col-md-8">
                              {{ article.content|html|replace({'&nbsp;':' '})|slice(0,100)|striptags }}...
                        </div>
                    </div>

                    <div class="font-italic text-muted mt-2"> Créé
                        le {{ article.createdat|localizeddate('none', 'none', null, timezone, 'eeee d MMMM Y à HH:mm') }}
                        <br>Par <span class="text-redchiefs">{{ article.userId.username }}</span></div>
                </div>
            </div>
        {% endfor %}
        <div class="pagination">
            {{ knp_pagination_render(articles) }}
        </div>
    </div>
{% endblock %}

templates/Front/comments.html.twig
{% block comments %}
    {% if comments|length > 0 %}
        <div class="div alert-danger commentsAlert">
            ERROR
        </div>
        {% for comment in comments %}
            {% if comment.status > 0 %}
                <hr>

                <div class="comment">
                    <div class="row">
                        <p class="font-weight-bold col-md-8"> {{ comment.username }}: <br>
                            <span class="font-italic font-weight-light">Le  {{ comment.created_at|localizeddate('none', 'none', null, timezone, 'eeee d MMMM Y à HH:mm') }}</span>
                        </p>
                        {% if comment.status == 2 %}
                            <a href="{{ path('article_signalComment',{id: comment.id}) }}"
                               class="btn btn-success btn-signal col-md-2">Signaler</a>
                        {% endif %}
                    </div>
                    {% if comment.status == 1 %}
                        <p class="text-moderation">Ce commentaire a été soumis à la modération</p>
                    {% else %}
                        <p class="text-comment">{{ comment.content }}</p>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}

    {% else %}
        <hr>
        <p> Pas de Commentaires</p>
    {% endif %}

{% endblock %}

     {% block javascripts %}
         <script>

             function signalComment(event) {
                 event.preventDefault();

                 const url = this.href;
                 const content = $(this).parent().parent().children('p.text-comment');
                 const that = $(this);
                 $.ajax({
                     url: url,
                     type: "POST",
                     dataType: "json",
                     // async: true,
                     success: function (data) {
                         $('.alert-danger').hide();
                         console.log(data);
                         content.html("Ce commentaire a été soumis à modération");
                         content.css('font-style', 'italic');
                         that.css('display', 'none');

                     },
                     error: function (data) {
                         console.log(data);
                         console.log(data['responseJSON'][0]);
                         $('.alert-danger').show();
                         $('.alert-danger').html(data['responseJSON'][0]);
                     }
                 });
             }

             document.querySelectorAll('a.btn-signal').forEach(function (link) {
             link.addEventListener('click', signalComment);
             })

         </script>
     {% endblock %}

templates/Front/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container mt-4">
        <h1>Bienvenue sur ChiefsFrance</h1>
        <div class="card mt-4">
            <h2 class="card-header bg-redchiefs text-light">
                Edito
            </h2>
            <div class="card-body">
                <div class="row no-gutters">

                    <div>
                     <p>  Bienvenue sur le site ChiefsFrance, créé par un fan des Chiefs pour les fans des Chiefs francophones.
                        A l'origine ce n'était qu'un simple compte twitter sans prétention ( <a href="https://twitter.com/chiefsfrance">@ChiefsFrance</a> ), puis avec le nombre d'abonnés l'idée de créer quelque chose de plus consistant commenca à germer, histoire de produire du contenu plus enrichi. Le compte twitter c'est en effet suffisant pour les lvetweets des matchs et de la draft, la publication des brèves mais plus compliqué de produire des analyses ou des bilans dignes vraiment d'intéret, sans compter le fait qu'elles seraient facilement oubliés.</p><br>

                       <p> Du coup, profitant de ma formation chez OpenClassroom de Dévellopeur Web, j'ai commencé à travailler à la création de ce site en fin d'année 2019. La première version ne comportait qu'un modeste blog, avant que les autres fonctionalités viennent l'enrichir. Je vous souhaite donc une bonne visite et n'hésitez pas à me contacter si vous voulez participer à la vie de ce site, via la rédaction d'articles, la participation au podcast, ou si vous avez une nouvelle fonctionnalitée.</p>

                        <p>#ChiefsKingdom<br>
                        Aldra Elonal,<br>
                        Créateur de ChiefsFrance,<br>
                            CM de @ChiefsFrance</p>

                    </div>
                </div>
            </div>
        </div>


        {% for article in articles %}
            <div class="card mt-4">
                <h2 class="card-header bg-redchiefs text-light">
                    <a class="text-light" href="{{ path('article', {id: article.id}) }}"> {{ article.title }} </a>
                </h2>
                <div class="card-body">
                    <p class="category btn btn-danger">{{ article.categoryId.name }}</p>
                    <div class="row no-gutters">
                        {% if article.imagename %}
                            <div class="col-md-4">

                                <img src="{{ vich_uploader_asset(article,'imageFile')|imagine_filter('article_thumb') }}"
                                     height="150" width="150"/>
                            </div>
                        {% endif %}
                        <div class="col-md-8"><p>
                            {{ article.content|html|slice(0,300)|raw}}...</p>
                        </div>
                    </div>

                    <div class="font-italic text-muted mt-2"> Créé
                        le {{ article.createdat|localizeddate('none', 'none', null, timezone, 'eeee d MMMM Y à HH:mm') }}
                        <br>Par <span class="text-redchiefs">{{ article.userId.username }}</span></div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}